### ISSUE TITLE
Cannot be installed from Mod Directory

### ISSUE THREAD

**Issue by apoapostolov** [Autmor/yourTurn#1]
![image](https://user-images.githubusercontent.com/4083812/172053689-073abc23-d0b7-44b5-bbbd-a5342893c582.png)

**Comment by kalxen** [comment]
Was about to post same that there is no manifest.  This looks really cool, and I'd love to try it.

**Comment by Autmor** [comment]
Thanks! I think I have fixed it.

**Comment by kalxen** [comment]
Your module.json in release 1.4 is still missing the URL, Download, and manifest lines required to install correctly.

**Comment by Autmor** [comment]
Ah shit, I will fix that as soon as I get back home to my desktop. Thank you!

**Comment by rogerioavsilva** [comment]
I did some changes that worked fine for me ->> https://github.com/Autmor/yourTurn/pull/2 

see here as well
https://github.com/Autmor/yourTurn/blob/d09ed19f57703844fa97b5581ad6653611be23ca/module.json

**Comment by Armandeus66** [comment]
> I did some changes that worked fine for me ->> #2
> 
> see here as well https://github.com/Autmor/yourTurn/blob/d09ed19f57703844fa97b5581ad6653611be23ca/module.json

Your link gives an error when attempting to install by copying it into the Foundry mod installer ("did not provide a valid manifest file").

I'm looking forward to installing Your Turn when Autmor updates the link.

**Comment by Autmor** [comment]
Okay it should be working now! I'm sorry for the wait!

**Comment by Armandeus66** [comment]
Thanks! I could install it!
